# Generated by Django 5.0 on 2023-12-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
