# Generated by Django 5.0 on 2024-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_rentcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
            ],
        ),
    ]
