# Generated by Django 5.0 on 2024-01-19 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_newshop'),
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rentitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='Userdocs/')),
                ('description', models.TextField()),
                ('rate', models.TextField()),
                ('features', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_rentcategory')),
            ],
        ),
    ]
