# Generated by Django 5.0 on 2024-02-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_tbl_sellercomplaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_sellercomplaint',
        ),
    ]
