# Generated by Django 5.0 on 2024-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0012_tbl_productgallery_rentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rentitem',
            name='offerstatus',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
