# Generated by Django 5.0 on 2024-02-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_services',
        ),
    ]
