# Generated by Django 5.0 on 2024-01-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_remove_tbl_newseller_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_newuser',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
