# Generated by Django 5.0 on 2024-01-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_alter_tbl_newuser_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newseller',
        ),
    ]
