# Generated by Django 5.0 on 2024-01-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_newshop'),
        ('Guest', '0005_delete_tbl_newseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('photo', models.FileField(upload_to='Userdocs/')),
                ('proof', models.FileField(upload_to='Userdocs/')),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(default=0, max_length=50, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
