# Generated by Django 5.0 on 2024-01-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_cart',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='tbl_cart',
            old_name='product_id',
            new_name='product',
        ),
    ]
