# Generated by Django 5.0 on 2024-01-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_tbl_rentitem_seller'),
        ('User', '0002_rename_booking_id_tbl_cart_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_rentitem'),
        ),
    ]
