# Generated by Django 5.0 on 2024-02-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_serviceprovider'),
        ('User', '0004_tbl_servicebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_usercomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50)),
                ('complaintdate', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_newuser')),
            ],
        ),
    ]
