# Generated by Django 5.0 on 2024-03-02 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_adminlogin'),
        ('User', '0009_tbl_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_userrating',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_newseller'),
        ),
        migrations.AddField(
            model_name='tbl_userrating',
            name='serviceprovider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_serviceprovider'),
        ),
    ]
