# Generated by Django 5.0 on 2024-03-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_tbl_userrating_seller_tbl_userrating_serviceprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_servicebooking',
        ),
    ]
